services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    networks:
      - ollama
    volumes:
      - /usr/share/ollama:/root/.ollama
    ports:
      - 11434:11434

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - /usr/share/open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8090:8080
    environment:
      - 'WEBUI_AUTH=False'
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ollama

networks:
  ollama:

